spring.application.name=user-skill-api
# ====================
# DATABASE CONFIG
# ====================
spring.datasource.url=jdbc:postgresql://localhost:5432/skillit
spring.datasource.username=sampleuser
spring.datasource.password=sampleuser
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# # ====================
# # GOOGLE OAUTH CONFIG
# # ====================
# spring.security.oauth2.client.registration.google.client-id=71081266017-40c73ebg5o7tthk1896p03hjv410029p.apps.googleusercontent.com
# spring.security.oauth2.client.registration.google.client-secret=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
# spring.security.oauth2.client.registration.google.scope=openid,profile,email
# spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
#
# spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
# spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
# spring.security.oauth2.client.provider.google.user-info-uri=https://openidconnect.googleapis.com/v1/userinfo
# spring.security.oauth2.client.provider.google.user-name-attribute=sub
#
# google.client-id=YOUR_GOOGLE_CLIENT_ID
jwt.secret=19Nz3vbjeEHra9+2pdZKvQsg/wcZ7wOuofo0F3AlloM=
# ====================
# SERVER
# ====================
server.port=8080
